language: php

php:
    - 5.3
    - 5.4
    - 5.5
  
install:
    - composer install --dev --prefer-source
    - vendor/bin/phpunit test/ChecksumTest/
  
script:
    - vendor/bin/php-cs-fixer fix -v --dry-run .